In [58]:
#Check the Data Type of an Array

import numpy as np

arr = np.array([1, 2, 3, 4])

arr.dtype

dtype('int32')

In [60]:
#Change any int value to a float one and check the result (say 4 as 4.0)

arr = np.array([1, 2.0, 3, 4.0])
print(arr) 
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [63]:
#similarly an array containing strings

arr = np.array(['strawberries', 'banana', 'cherry'])

arr.dtype

#U stands for unicode string
#6 represents the maximum no of characters present in the string

dtype('<U12')

In [64]:
#--Creating Arrays With a Defined Data Type

#dtype allows to define the expected data type of the array elements:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

#Here `b '1' byte string 
#means the array holds strings in byte format.

#Byte Strings: In Python, strings can be represented as byte strings 
#(which are sequences of bytes) by prefixing them with a b, 
#like b'hello'. This indicates that the string is not a regular Unicode string
#but a byte string.

[b'1' b'2' b'3' b'4']
|S1


In [65]:
#Similarly, the size can be defined for i, u, f, s and U

#For example

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [66]:
# Converting Data Type on Existing Arrays

#Can be done by astype() method by creating a copy of the array

#astype() function creates a copy of the array, 
#then allows you to specify the data type as a parameter.

#Qn: Change data type from float to integer by using 'i' as parameter value.

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')#creating a copy of the array
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [67]:
#Qn: Change data type from integer to boolean 
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

#0 is considered False in a boolean context.
#Any non-zero value is considered True in a boolean context.

[ True False  True]
bool


In [68]:
#-----Creating Structured Arrays-----

dtype = np.dtype([('name', 'U20'), ('age', np.int32), ('grade', np.float64)])

In [69]:
data = np.array([('Alice', 25, 4.8), ('Bob', 23, 3.9), ('Charlie', 27, 4.5)], dtype=dtype)

In [70]:
# Access the 'name' field
print(data['name'])


['Alice' 'Bob' 'Charlie']


In [71]:
# Access the 'age' field
data['age']

array([25, 23, 27])

In [72]:
# Access the 'grade' field
data['grade']

array([4.8, 3.9, 4.5])

In [73]:
#Manipulating Structured Arrays
# Qn ---Sorting---

#sort the data array based on the 'age' field in descending order 
sorted_data = np.sort(data, order='age')[::-1]
print(sorted_data)



[('Charlie', 27, 4.5) ('Alice', 25, 4.8) ('Bob', 23, 3.9)]


In [74]:
#--Aggregations---

average_age = np.mean(data['age'])
maximum_grade = np.max(data['grade'])

print(average_age)  
print(maximum_grade)  


25.0
4.8


In [75]:
#Filtering ( based on certain conditions)

dtype = np.dtype([('name', 'U20'), ('age', np.int32), ('grade', np.float64)])
data = np.array([('Alice', 25, 4.8), ('Bob', 23, 3.9), ('Charlie', 27, 4.5)], dtype=dtype)

filtered_data = data[data['age'] < 26]
print(filtered_data)

[('Alice', 25, 4.8) ('Bob', 23, 3.9)]


In [ ]:
#Concatenation

new_data = np.array([('David', 28, 4.3), ('Eve', 22, 3.7)], dtype=dtype)
concatenated_data = np.concatenate((data, new_data))
print(concatenated_data)

In [ ]:
#vertical Concatenation

data1 = np.array([('Alice', 25, 4.8), ('Bob', 23, 3.9), ('Charlie', 27, 4.5)], dtype=dtype)
data2 = np.array([('David', 28, 4.3), ('Eve', 22, 3.7), ('John', 28, 4.0)], dtype=dtype)
concatenated_data = np.vstack((data1, data2))
print(concatenated_data)

In [ ]:
#Adding or modifying the field names

#Qn: For an original structured array data with fields name and age, 
#add another field named height:
# Original structured array

#1. Create the dtype
dtype = np.dtype([('name', 'U10'), ('age', 'i4')])
data = np.array([('Alice', 25), ('Bob', 30)], dtype=dtype)

# Add a new field 'height'
new_dtype = np.dtype(data.dtype.descr + [('height', 'f4')])

# Create a new array with the extended dtype
new_data = np.zeros(data.shape, dtype=new_dtype)

# Copy existing data
for name in data.dtype.names:
    new_data[name] = data[name]

# Add new data for the 'height' field
new_data['height'] = [160.5, 170.0]

print(new_data)

In [ ]:
#Create a structured array for six employees with the fields: name (string), 
#salary (float), and years_of_experience (integer). 
#Populate the array with some sample data and then sort the array 
#based on salary in ascending order. Print the sorted array.

# Step 1: Define the structured data type
dtype = np.dtype([('name', 'U20'), ('salary', 'f4'), ('years_of_experience', 'i4')])

# Step 2: Create the structured array with sample data
employees = np.array([
    ('Alice', 75000.0, 5),
    ('Bob', 50000.0, 2),
    ('Charlie', 60000.0, 3),
    ('David', 85000.0, 7),
    ('Eve', 95000.0, 10),
    ('Frank', 70000.0, 4)
], dtype=dtype)

# Step 3: Sort the array based on salary in ascending order
sorted_employees = np.sort(employees, order='salary')

# Step 4: Print the sorted array
print("Employees sorted by salary (ascending order):")
print(sorted_employees)